
version: "3.3"

services:
  ember:
    image: node:alpine
    working_dir: /usr/src
    command: ['npm', 'start']
    ports:
      - 4200:4200
    volumes:
      - ./:/usr/src
    environment:
      - API_HOST
      - API_PORT
      - API_ROUTE
